# Alert Filter Demo Configuration

# Paths
paths:
  data_dir: "./data"
  model_dir: "./models"
  output_dir: "./output"
  feedback_dir: "./feedback"

# Model parameters
model:
  autoencoder:
    model_path: "./models/autoencoder_model.pt"  # Path to the real autoencoder model
    # threshold: 0.026970019564032555  # Default threshold for anomaly detection
    threshold: 0.0252244  # Default threshold for anomaly detection

  alert_filter:
    model_path: "./models/alert_filter_model.pt"
    latent_dim: 16
    hidden_dim: 32
    learning_rate: 0.001
    epochs: 50
    batch_size: 32

# Demo settings
demo:
  num_anomalies: 10
  data_path: "test"  # Use "train", "val", or "test" dataset
  random_seed: 42
  show_details: true
  save_results: true
