FROM ubuntu:latest
LABEL authors="sse"

ENTRYPOINT ["top", "-b"]# Dockerfile for NWDAF Data Producer
FROM python:3.9-slim

WORKDIR /app

# Install dependencies
RUN pip install --no-cache-dir pandas numpy kafka-python

# Copy application code
COPY ./NWDAF\ Data\ Producer.txt /app/nwdaf_data_producer.py

# Run the application
CMD ["python", "/app/nwdaf_data_producer.py", "--config", "/app/config/config.json"]