channels:
- conda-forge
dependencies:
- python=3.12.3
- pip<=25.0.1
- pip:
  - dash==2.18.2
  - fire==0.7.0
  - flwr[simulation]==1.16.0
  - flwr-datasets==0.5.0
  - matplotlib==3.10.1
  - mlflow==2.20.4
  - numpy==1.26.4
  - optuna==4.2.1
  - pandas==2.2.3
  - plotly==6.0.0
  - python-dotenv==1.0.1
  - pytorch-triton-rocm==3.2.0
  - pytorch-forecasting==1.3.0
  - PyYAML==6.0.2
  - requests==2.32.3
  - scikit-learn==1.6.1
  - seaborn==0.13.2
  - torch==2.6.0+rocm6.2.4
  - torchinfo==1.8.0
  - tqdm==4.67.1
name: mlflow-env
