FROM python:3.11-slim

WORKDIR /app

# Install dependencies
RUN pip install --no-cache-dir \
    torch==2.7.0 \
    numpy==2.2.6 \
    pandas==2.2.3 \
    kafka-python \
    mlflow==2.22.0 \
    scikit-learn==1.6.1

# Copy the detector script
COPY detector.py /app/

# Run the detector
CMD ["python", "/app/detector.py"]