FROM python:3.12-slim

WORKDIR /app
# Set PYTHONPATH to include the privateer_ad package
ENV PYTHONPATH="/app:${PYTHONPATH}"

# Install dependencies
RUN pip install --no-cache-dir \
    pandas==2.2.3 \
    kafka-python==2.2.10 \
    pydantic==2.11.5 \
    pydantic-settings==2.9.1

# Copy the producer script
COPY demo/producer.py producer.py

# Run the producer
CMD ["python", "/app/producer.py"]