FROM python:3.12-slim

WORKDIR /app
# Set PYTHONPATH to include the privateer_ad package
ENV PYTHONPATH="/app:${PYTHONPATH}"

# Install dependencies
RUN pip install --no-cache-dir \
    pandas==2.2.3 \
    kafka-python==2.2.10

# Copy the producer script
COPY producer.py /app/producer.py

# Run the producer
CMD ["python", "/app/producer.py"]

